-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE TABLE IF NOT EXISTS public.trade (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  side character varying COLLATE pg_catalog."default",
  price real,
  size real,
  "timestamp" timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trade_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE
  IF EXISTS public.trade OWNER to postgres;

GRANT ALL ON TABLE public.trade TO anon;

GRANT ALL ON TABLE public.trade TO authenticated;

GRANT ALL ON TABLE public.trade TO postgres;

GRANT ALL ON TABLE public.trade TO service_role;

COMMENT ON TABLE public.trade IS 'Trade History';

CREATE TABLE IF NOT EXISTS public.oi (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  value integer,
  "timestamp" timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT oi_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE
  IF EXISTS public.oi OWNER to postgres;

GRANT ALL ON TABLE public.oi TO anon;

GRANT ALL ON TABLE public.oi TO authenticated;

GRANT ALL ON TABLE public.oi TO postgres;

GRANT ALL ON TABLE public.oi TO service_role;

COMMENT ON TABLE public.oi IS 'OpenInterest';

CREATE TABLE IF NOT EXISTS public.liquidation (
  id uuid NOT NULL,
  side character varying COLLATE pg_catalog."default",
  price real,
  qty real,
  "timestamp" timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT liquidation_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE
  IF EXISTS public.liquidation OWNER to postgres;

GRANT ALL ON TABLE public.liquidation TO anon;

GRANT ALL ON TABLE public.liquidation TO authenticated;

GRANT ALL ON TABLE public.liquidation TO postgres;

GRANT ALL ON TABLE public.liquidation TO service_role;

COMMENT ON TABLE public.liquidation IS 'Liquidation';